language: python
sudo: false
python:
  - 3.7.4

before_install:
  - pip install poetry
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - poetry install

script:
  - make lint
  - make test

env:
  - SECRET_KEY=secret
    GITHUB_AUTH_TOKEN=secret
    GITHUB_WEBHOOK_TOKEN=secret
