language: python  # 3.6 by default

os: linux

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry install

script:
  - make check

env:
  - SECRET_KEY=secret
    GITHUB_AUTH_TOKEN=secret
    GITHUB_WEBHOOK_TOKEN=secret

cache: pip
