[tool.poetry]
name = "hexlet-friends"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.2"
python-dotenv = "^0.10.3"
django-bootstrap4 = "^1.0"
requests = "^2.22"

[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.12.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
